# .net application

variables: 
  IMAGE_NAME: telegit
    
before_script: 
  - echo "export GITLAB_SECRET_TOKEN=$CI_ENV_GITLAB_SECRET_TOKEN"
  - echo "export TELEGRAM_API_TOKEN=$CI_ENV_TELEGRAM_API_TOKEN"
  - echo "export TELEGRAM_CHAT_ID=$CI_ENV_TELEGRAM_CHAT_ID"

stages:
  - build
  - startup
    
build:
  stage: build
  only:
      - main
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - sudo docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - sudo docker images -a | grep $IMAGE_NAME | grep -v latest | awk '{print $3}' | xargs sudo docker rmi -f
      
startup:
    stage: startup
    only:
      - main
    script:
      - docker run -d -p 6000:6000 $IMAGE_NAME:latest