variables: 
  IMAGE_NAME: telegit
    
before_script: 
  - echo "export GITLAB_SECRET_TOKEN=$GITLAB_SECRET_TOKEN"
  - echo "export TELEGRAM_API_TOKEN=$TELEGRAM_API_TOKEN"
  - echo "export TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID"

stages:
  - build
  - startup
    
build:
  stage: build
  only:
      - main
  tags:
    - photon
    - infrastructure
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    # - docker images -a | grep $IMAGE_NAME | grep -v latest | awk '{print $3}' | xargs docker rmi -f
      
startup:
    stage: startup
    only:
      - main
    tags:
      - photon
      - infrastructure
    script:
      - docker run -d -p 6000:6000 $IMAGE_NAME:$CI_COMMIT_SHORT_SHA